### ISSUE TITLE
Blaze Powder/Nether Fortresses

### ISSUE THREAD

**Issue by Speedy7524** [amanocchi/NAFTV-ISSUES#1]
I am unable to find Blaze Powder.  I can't find a fortress or Blaze in the Nether.  Am I missing something?  Thanks!

**Comment by amanocchi** [comment]
As the Quest says, you need to do this with chemistry. The quest shows wich elements you need. 

You need to put the elements in a chemical combiner

Actually, there are some nether fortress but they are very rare

**Comment by Speedy7524** [comment]
I’m on the Thermo Generator quest in step 2.  Is this the quest you are referring to?  Some of my quest descriptions are just black boxes with no text. Thanks

Sent from my iPhone

On May 2, 2020, at 2:44 AM, amanocchi <notifications@github.com> wrote:

﻿

As the Quest says, you need to do this with chemistry. The quest shows wich elements you need.

**Comment by Speedy7524** [comment]
Ok, went the chemistry route and I am getting the blaze powder.  Thanks.  Are you getting descriptions to show up on the quests?  Is it just my setup?

**Comment by Speedy7524** [comment]
Looks like quest Title and Subtitle are working properly.  The blank description is when I mouse over an item in a quest.  Don't think that matters much.  I think the quest you were referring to is in stage 3, the Thermo plates in the Thermo Generator recipe require blaze powder.  Thanks for the pack.

**Comment by amanocchi** [comment]
I'll 

> Looks like quest Title and Subtitle are working properly. The blank description is when I mouse over an item in a quest. Don't think that matters much. I think the quest you were referring to is in stage 3, the Thermo plates in the Thermo Generator recipe require blaze powder. Thanks for the pack.

I'll edit the Recipe. I'll change the Blaze Powder with Lava Buckets. The Quest Bug with the Blank description is from the FTBQuest mod itself cause the 1.15.2 version is currently in Alpha i am unable to fix this 

Structures are not generating i'll add a wither skeleton spawn egg recipe
